# Generated by Django 3.1.7 on 2021-04-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='Дата Создания!')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голосы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=200)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choices', to='webapp.poll')),
            ],
            options={
                'verbose_name': 'Выбор',
                'verbose_name_plural': 'Выборы',
                'db_table': 'Choices',
            },
        ),
    ]
